config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  root to: "posts#index"
  get 'my_friends', to: 'accounts#my_friends'
  get 'search_friends', to: 'accounts#search'
  get 'view_connections', to: 'accounts#view_connections'
  get 'viewed_my_account', to: 'views#index'
  get 'search_new', to: 'accounts#search_new'
  
  resources :friendships, only: [:create, :destroy]
  resources :accounts, only: [:show, :destroy]
  resources :posts, only: [:new, :create, :show, :index, :destroy]
  resources :likes, shallow: true
  resources :comments, only: [:index, :create, :destroy], shallow: true
  resources :requests
  resources :views
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :views, dependent: :destroy

  has_one_attached :image, :dependent => :destroy
  validates :image, presence: false, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  # def friends
  #   Friendship.where(account_one_id: id).or.where(account_two_id: id).pluck(:account_one_id, :account_two_id).flatten.uniq
  # end

  def self.first_name_matches(param)
    matches('first_name',param)
  end

  def self.last_name_matches(param)
    matches('last_name',param)
  end
  def self.email_matches(param)
    matches('email',param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_account(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friends)
    !self.friends.where(id: id_of_friends).exists?
  end

  def has_requested?(friend_id)
    Request.where(account_id: current_account.id, friend_id: friend_id).present?
  end

  
end

app/models/account_observer.rb
class AccountObserver < ActiveRecord::Observer
  observe :account
  def before_destroy(account)
    Friendship.where(friend_id: account.id).destroy_all
    Request.where(friend_id: account.id).destroy_all
    View.where(friend_id: account.id).destroy_all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :account
  belongs_to :friend, class_name: 'Account', foreign_key: :friend_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :account

  validates :account_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, -> {order(:created_at => :desc)}, dependent: :destroy
  has_many :comments, -> {order(:created_at => :desc)}, dependent: :destroy
  belongs_to :account
  has_many_attached :images, :dependent => :destroy
  validates :description, presence: true, length: {minimum: 2, maximum: 100}
  validates :images, presence: false, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }

  def is_liked account
    Like.find_by(account_id: account.id, post_id: id)
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :account
  belongs_to :friend, class_name: 'Account'

  # validates :account, uniqueness: { scope: :friend }
  validates_uniqueness_of :account, scope: [ :friend, :status ]
end

app/models/request_observer.rb
class RequestObserver < ActiveRecord::Observer
  observe :request
  def before_destroy(request)
   
  end
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :account
  belongs_to :friend, class_name: 'Account'

  validates_uniqueness_of :account, scope: [ :friend]
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_account!
  
  # def save_like
  #   @like = Like.new(post_id: params[:post_id], account_id: current_account.id)
  #   @post_id = params[:post_id]

  #   respond_to do |format|
  #     format.js {
  #       if @like.save
  #         @success: true 
  #       else
  #         @success: false 
  #       end

  #       render "post/like"
  #     }
  #   end
  # end
  def create
    @like = current_account.likes.build(like_params)
    @post = @like.post
    if @post == nil
      print('asdf')
      flash[:alert] = "Post has been deleted"
    end
    if @like.save
      respond_to :js
    else 
      flash[:alert] = "something went wrong"
    end
    
  end 

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    else 
      flash[:alert] = "something went wrong"
    end
  end
  
  def index
    @likes = Like.all.includes(:post, :account).order(created_at: :desc)
  end

  private
  def like_params
    params.permit :post_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index 
    @posts = Post.all.includes(:account, :likes).with_attached_images.order('created_at DESC')
  end
  def create
    @post = Post.new(params.require(:post).permit(:description, :images))
    @post.account = current_account
    @post.images.attach(params[:post][:images])
    if @post.save
      flash[:notice] = "Post created successfully"
      redirect_to account_path(current_account) 
    else
      flash[:alert] = "Please upload an image file (<5mb)."
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @likes = @post.likes.includes(:account, :like)
    @comment = Comment.new
    @is_liked = @post.is_liked(current_account)
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to account_path(current_account)
end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/friends/_list.html.erb
  
    <div class="row">
    <% @friends.each do |friend|%>
    <div class="col-md-4 mt-2">
      <div class="card text-center" style="width: 10rem;">
        <div class="card-body">
        <% if friend.image.present? %>
          <%= image_tag(friend.image.variant(resize: "100x100"), :class => "rounded-circle")%>
        <% else %>
          <%= image_tag("empty_profile.jpeg", :size => '100x100', :class => "rounded-circle")%>
        <% end %><br/>
        <%= link_to friend.full_name, account_path(friend)%>
        <%= link_to 'Disconnect', friendship_path(friend), method: :delete, data: {confirm: 'Are you sure?'},
                                          class: 'btn btn-sm btn-danger' %> <br/>
          </div>
      </div>
      </div>
    <% end %>
    </div>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="position: fixed;top: 0; width: 100%;z-index:1;">
    <div class="container">
        <%= link_to 'CONNECTED', root_path, class: 'navbar-brand' %>
        <% if current_account %> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item <%= 'like-active' if request.path == account_path(current_account) %>">
                        <%= link_to 'My Account', account_path(current_account), class: 'nav-link' %>
                    </li>
                    <li class="nav-item <%= 'like-active' if request.path == my_friends_path %>">
                    <%= link_to 'My Friends', my_friends_path, class: 'nav-link' %>
                </li>
                <li class="nav-item <%= 'like-active' if request.path == search_new_path %>">
                    <%= link_to 'Search', search_new_path, class: 'nav-link' %>
                </li>
                <li class="nav-item <%= 'like-active' if request.path == new_post_path %>">
                    <%= link_to 'New Post', new_post_path, class: 'nav-link' %>
                </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to edit_account_registration_path, class: 'dropdown-item' do %>
                            <%= fa_icon 'edit' %> Edit profile
                        <% end %>
                        
                        <%= link_to "Viewers", viewed_my_account_path(account_id: current_account), class: 'dropdown-item'%></td>
                        <% if !current_account.company?%>
                        <div class="dropdown-divider"></div>
                        <%= link_to 'My Requests', requests_path, class: 'dropdown-item' %>
                        </div>
                        <% end %>
                    </li>
                    
                </ul>
                <ul class='navbar-nav ml-auto'>
                    <li class='nav-item user-name'>
                        <%= fa_icon 'user' %> <%= link_to current_account.full_name, account_path(current_account) %>
                        <% if current_account.company? %>
                            <i class="fa fa-check" style="color: #00FFFF;"></i>
                        <% end %>
                    </li>
                    <li class='nav-item'>
                        <%= link_to("Logout", destroy_account_session_path,
                            class: "btn btn-danger logout-button", method: :delete,  data: {confirm: 'Are you sure?'})%>
                    </li>
                </ul>
                
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Connected</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation"%>
    <div class="container mt-5" style="margin-top: 50px;">
    <br/><br/>
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/views/index.html.erb
<h2> Viewers </h2><br/>
<% if @views.count == 0 %>
<h4> No one viewed your account</h4>
<% else %>
<h4><%= @views.count %> <%=  (@views.count == 1)? "person": "people"%> viewed your account in the past one week</h4><br/>
<div class="row">
  <div class="col-9">  
    <table class="table table-bordered table-hover"> 
      <thead>
        <tr>
          <th scope="col">Name</th>
        </tr>
      </thead>
      <tbody>
        <% @views.each do |view|%>
          <% if !(view.account == current_account)  %>
            <% if is_valid(view)%>
              <tr>  
              <td style="background-color: lightgreen;">
              <div class="row">
              <div class="col-md-10">
                <%= link_to view.account.full_name, account_path(id: view.account.id) %><br/>
                <span class="date text-black-50">Viewed <%= time_ago_in_words(view.created_at) %> ago</span>
              </div>
              <div class="text-right col-md-2">
              <%= link_to "x", view_path(view), method: :delete, class: 'btn btn-sm btn-danger'%>
              </div>               
                </div>
                </td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>