config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  root to: "posts#index"
  get 'my_friends', to: 'accounts#my_friends'
  get 'search_friends', to: 'accounts#search'
  get 'view_connections', to: 'accounts#view_connections'
  get 'viewed_my_account', to: 'views#index'
  get 'search_new', to: 'accounts#search_new'
  
  resources :friendships, only: [:create, :destroy]
  resources :accounts, only: [:show, :destroy]
  resources :posts, only: [:new, :create, :show, :index, :destroy]
  resources :likes, shallow: true
  resources :comments, only: [:index, :create, :destroy], shallow: true
  resources :requests
  resources :views
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, -> {order(:created_at => :desc)}, dependent: :destroy
  has_many :comments, -> {order(:created_at => :desc)}, dependent: :destroy
  belongs_to :account
  has_many_attached :images, :dependent => :destroy
  validates :description, presence: true, length: {minimum: 2, maximum: 100}
  validates :images, presence: false, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }

  def is_liked account
    Like.find_by(account_id: account.id, post_id: id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index 
    @posts = Post.all.includes(:account, :likes).with_attached_images.order('created_at DESC')
  end
  def create
    @post = Post.new(params.require(:post).permit(:description, :images))
    @post.account = current_account
    @post.images.attach(params[:post][:images])
    if @post.save
      flash[:notice] = "Post created successfully"
      redirect_to account_path(current_account) 
    else
      flash[:alert] = "Please upload an image file (<5mb)."
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @likes = @post.likes.includes(:account, :like)
    @comment = Comment.new
    @is_liked = @post.is_liked(current_account)
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to account_path(current_account)
end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= form_for [Comment.new] , :html => {:class => "w-100"}, remote: true do |f|%>
<%= f.hidden_field :account_id, value: current_account.id%>
<%= f.hidden_field :post_id, value: post.id%>
<%= f.text_field :content, class: "form-control comment-input border-0 comment-cursor",
  placeholder: "Add a comment...", autocomplete: :off%>
<% end %>

app/views/posts/_comment_full.html.erb
<div class="container">
<div class="bg-light p-2">
  <div class="row actions" id="comment-form-post-<%= post.id.to_s%>">
    <%= render "comment_form", {post: post}%>
  </div>
</div>
</div>
<div id="comment-post-<%= post.id.to_s%>">
  <%= render "comment_list", {post: post}%>
</div>

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment|%>
  <div class="mb-2 ml-3 text-left">
    <% if comment.account == current_account%>
      <%= link_to "Delete", comment_path(comment),
          method: :delete, remote: true, class: "fa-solid fa-x delete-comment mr-3"%>
    <% end %>
    <span> <strong> <%= comment.account.full_name%> </strong> </span>
    <span> <%= comment.content %></span>
  </div>
<% end %>

app/views/posts/_like_icon.html.erb
<% if is_liked.present? %>
  <%= link_to "Liked", like_path(is_liked), method: :delete, remote: true,
  class: "like p-2 cursor like-active fa fa-thumbs-o-up"%>
<% else %>
  <%= link_to "Like", likes_path(post_id: post.id), method: :post, remote: true,
  class: "like p-2 cursor fa fa-thumbs-o-up"%>
<% end %>

app/views/posts/_like_text.html.erb
<div class="text-left ml-3 <%= (likes.count > 0)? "mt-1 p-1": "" %>">
<% likes.each.with_index do |like, index| %> 
  <% if likes.size == 1%>
    <strong><%=  link_to like.account.full_name, account_path(like.account) %> </strong>
  <% elsif like == likes.last %>
    and
    <strong><%= link_to like.account.full_name, account_path(like.account)%></strong>
  <% elsif index > 1%>
    and 
    <button type="button" class="btn btn-primary other-likes" data-toggle="modal" data-target="#exampleModalCenter-<%=likes[0].id%>">   
    <strong> <%= (likes.size-index).to_s %> others </strong>
    </button>
    <%= render 'posts/list_likes', {likes: likes}%>
    
    <%break%>
  <% elsif index==likes.size-2 || index == 1%>
    <strong> <%=  link_to like.account.full_name, account_path(like.account)%> </strong>
  <% else %>
    <strong> <%=  link_to like.account.full_name, account_path(like.account) %> </strong>,
  <% end %> 
  
<%end %>
<% if likes.count>0%>
liked this
<% end %>
</div>

app/views/posts/_list_likes.html.erb
<div class="modal fade" id="exampleModalCenter-<%=likes[0].id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Post liked by</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <center>
      <div class="modal-body">
        <% likes.each do |like| %>
          <%= link_to like.account.full_name, account_path(like.account)%><br/>
        <% end %>
      </div>
      </center>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>  

app/views/posts/_list_posts.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
$(".comment-post").hide();
window.onload = function() {
    var reloading = sessionStorage.getItem("reloading");
    if (reloading) {
        $(".comment-post").hide();
    }
}

function toggleComment(post_id){
  $(".comment-icon-post-"+post_id).toggle("fast");
}
// $(document).ready(function(){
//   $(".comment-post").hide();
//   $(".comment").click(function(){
//     $(".comment-post").toggle("fast");
//   });
// });
</script>

<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="bg-white card-header font-italic">
        <div class="bg-white">
            <div class="d-flex flex-row user-info">
            <% if post.account.image.present? %>
              <%= image_tag(post.account.image.variant(resize_to_fill: [40, 40]), class: "rounded-circle") %>
            <% else %>
              <%= image_tag ("empty_profile.jpeg"), class: "rounded-circle profile_pic"%>
            <% end %>
              <div class="d-flex flex-column justify-content-start ml-2">
                <span class="d-block font-weight-bold name"><%= link_to post.account.full_name, account_path(post.account) %> 
                  <% if post.account.company? %>
                      <i class="fa fa-check" style="color: #00FFFF;"></i>
                  <% end %>
                  </span>
                  <span class="date text-black-50 text-left"><%= time_ago_in_words(post.created_at) %> ago</span>
                  </div>
                 <% if Account.find(post.account_id) == current_account%>
                    <div><p align="right"><%= link_to "Delete", post_path(post), class: "btn btn-outline-danger float-right delete-button-in-acc", method: :delete, data: {confirm: "Are you sure?"} %></p></div>
                      <% end %>
            </div>            
        </div>
      </div>          

         <div class="mt-1">
         <% if post.images.count == 1 %>
          <%= image_tag post.images.first.variant(resize: "450x450") %>
          <% elsif post.images.count > 1 %>
          <div id="carouselExampleControls-<%= post.id.to_s %>" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
          <% post.images.each do |photo| %>
            <% if photo == post.images.first %>
              <div class="carousel-item active">
            <% else %>
              <div class="carousel-item">
            <% end %>
            <%= image_tag photo.variant(resize: "450x450") %>
            </div>
          <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls-<%= post.id.to_s %>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls-<%= post.id.to_s %>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <% end %>
        </div>
          <div class="card-body text-left">
            <p class="card-text"><%= truncate(post.description, length: 100) %></p>
            </div>

            <div class="d-flex justify-content-center row">
              <div class="col-md-12 ">
                  <div class="d-flex flex-column comment-section">
                      <div class="card bg-white">
                          <div class="d-flex flex-row fs-12 mt-2">
                              <!-- <div class="like p-2 cursor"><i class="fa fa-thumbs-o-up"><span class="ml-1"  >Like</span></i></div> -->
                              
                              <div id="like-icon-post-<%= post.id.to_s%>" class="ml-5">
                              <%= render "posts/like_icon", {is_liked: post.is_liked(current_account), post: post}%>
                              </div>
                              <div class="like cursor comment ml-5"><button onclick="toggleComment(<%= post.id.to_s%>)" class="like-button"><i class="fa fa-commenting-o"><span class="ml-1">Comment</span></i></button></div>
                              
                          </div>
                          <div class="card bg-white mt-2">
                            <div id="like-text-post-<%= post.id.to_s %>">
                              <%= render "posts/like_text", {likes: post.likes}%>
                            </div>
                          </div>
                      </div>
                      <div class="comment-icon-post-<%= post.id.to_s%> comment-post">
                        <%= render "posts/comment_full", {post: post} %>
                      </div>
                    </div>
            </div>
          </div>
      </div>
    </div>
  </div>
  

      

app/views/posts/index.html.erb
<div class="row">
<div class="container-fluid col-3">
<%= form_with model: [Post.new], local: true do |f| %>
  
  <div class="card">
  <div class="card-body">

    <div class="mb-3">
      <%= f.label :description, { class: "form-label"} %>
      <%= f.text_field :description, { class: "form-control", placeholder: "Enter Description", required: true } %>
    </div>
    <div class="mb-3">
      <%= f.file_field :images, multiple: true   %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary" %>

  </div>
</div>
<% end %>
</div>
<div class="container-fluid col-8">
  <% @posts.each do |post| %>
  <% if current_account == post.account || Friendship.where(account_id: current_account.id, friend_id: post.account_id).present? || Friendship.where(account_id: post.account_id, friend_id: current_account.id).present? || current_account.company?%>
    <%= render 'list_posts', {post: post}%>
    <% end %>
  <% end %>
  <% @posts.each do |post| %>
    <% if !(current_account == post.account || Friendship.where(account_id: current_account.id, friend_id: post.account_id).present? || Friendship.where(account_id: post.account_id, friend_id: current_account.id).present? || current_account.company?)%>
      <% if  Account.find_by(id: post.account_id).company? && !(Friendship.where(account_id: current_account.id, friend_id: post.account_id).present?)%>
        <%= render 'list_posts', {post: post}%>
      <% end %>
    <% end %>
  <% end %>
</div>
<div class="container-fluid col-1">
</div>
</div>

app/views/posts/like.js.erb
$(".like-<%= @post_id %>").addClass("active");

app/views/posts/new.html.erb
<%= form_with model: @post, local: true do |f| %>
  
  <div class="card">
  <div class="card-body">

    <div class="mb-3">
      <%= f.label :description, { class: "form-label"} %>
      <%= f.text_field :description, { class: "form-control", placeholder: "Enter Description", required: true } %>
    </div>
    <div class="mb-3">
      <%= f.file_field :images, multiple: true   %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary" %>

  </div>
</div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
          <div class="bg-white p-2">
                  <div class="d-flex flex-row user-info"><img class="rounded-circle" src="<%= asset_path('')%>" width="40">
                      <div class="d-flex flex-column justify-content-start ml-2"><span class="d-block font-weight-bold name"><%= link_to @post.account.full_name, account_path(@post.account) %></span><span class="date text-black-50"><%= time_ago_in_words(@post.created_at) %></span></div>
                  </div>
                </div>
          </div>
         <% if @post.image.attached? %>
         <p>
          <%= image_tag @post.image %>
         </p>
         <% end %>
          <div class="card-body">
            <p class="card-text"><%= truncate(@post.description, length: 100) %></p>
            </div>
        </div>
      </div>
    </div>
</div>