config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  root to: "posts#index"
  get 'my_friends', to: 'accounts#my_friends'
  get 'search_friends', to: 'accounts#search'
  get 'view_connections', to: 'accounts#view_connections'
  get 'viewed_my_account', to: 'views#index'
  get 'search_new', to: 'accounts#search_new'
  
  resources :friendships, only: [:create, :destroy]
  resources :accounts, only: [:show, :destroy]
  resources :posts, only: [:new, :create, :show, :index, :destroy]
  resources :likes, shallow: true
  resources :comments, only: [:index, :create, :destroy], shallow: true
  resources :requests
  resources :views
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :views, dependent: :destroy

  has_one_attached :image, :dependent => :destroy
  validates :image, presence: false, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  # def friends
  #   Friendship.where(account_one_id: id).or.where(account_two_id: id).pluck(:account_one_id, :account_two_id).flatten.uniq
  # end

  def self.first_name_matches(param)
    matches('first_name',param)
  end

  def self.last_name_matches(param)
    matches('last_name',param)
  end
  def self.email_matches(param)
    matches('email',param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_account(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friends)
    !self.friends.where(id: id_of_friends).exists?
  end

  def has_requested?(friend_id)
    Request.where(account_id: current_account.id, friend_id: friend_id).present?
  end

  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_account! 
   
  def my_friends
    @friends = current_account.friends 
    @requests = Request.where(account_id: current_account, status: 0)
    # @left_account = Account.where(id: Friendship.where(friend_id: current_account).select(:account_id))
  end

  def search_new
    @accounts = Account.where.not(id: current_account)
    @first_friends = current_account.friends
    @second_friends = []
    @first_friends.each do |friend|
      friend.friends.each do |fr|
        @second_friends.append(fr)
      end 
    end
    @second_friends = @second_friends.uniq
    @suggested_accounts = []
    @accounts.each do |account|
      if !(Friendship.where(account_id: current_account,friend_id: account).exists? || Request.where(account_id: current_account, friend_id: account, status: 0).exists? || 
            Request.where(account_id: account, friend_id: current_account, status: 0).exists?)
        @suggested_accounts.append(account)
      end
    end
    # @suggested_accounts = @suggested_accounts.sample(4)
    temp = @suggested_accounts
    @suggested_accounts = @second_friends 
    if @suggested_accounts.count == 0
      @suggested_accounts = temp.sample(6)
    end 
  end

  def view_connections
    @account1 = Account.find(params[:account_id])
    @friends = @account1.friends
  end

  def search
    if params[:friend].present?
      @friends = Account.search(params[:friend])
      @friends = current_account.except_current_account(@friends)
      if @friends.count > 0 
        respond_to do |format|
          format.js { render partial: 'accounts/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "No Results Found"
          format.js { render partial: 'accounts/friend_result' }
        end
      end    
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: 'accounts/friend_result' }
      end
    end
  end

  def show
    @acc = Account.find(params[:id])
    if !(current_account == @acc) 
      if (View.where(account_id: current_account.id, friend_id: @acc.id).exists?)
        view = View.find_by(account_id: current_account.id, friend_id: @acc.id)
        view.created_at = Time.now
        view.save
      else
        View.create(account_id: current_account.id,friend_id: @acc.id )
      end
    end
    @posts = @acc.posts.order('created_at DESC')
    @friend = Friendship.find_by(account_id: @acc.id)
  end

  def my_account
    
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<% if @friends.count > 0 %>
<% if @friends %> 
  <div class="card card-header results-block">
  <table class="col-md-12" style="overflow-x: auto; border: 1px; width: 100%; padding: 35px;">
  <thead>
        <tr>
          <th scope="col" style="width: 150px; color: blue;">Name</th>
          <th scope="col" style="width: 200px; color: blue;">Email</th>
          <th scope="col" style="width: 120px; color: blue;">Actions</th>
        </tr>
      </thead>
    <tbody>
  <% @friends.each do |friend| %>
    <tr>
    <td><%= link_to friend.full_name, account_path(friend)%></td>
    <td><%= friend.email %></td>
    <td>
    <% if Request.where(account_id: current_account, friend_id: friend.id, status: 0).exists?%>
      <%= link_to 'Undo Request', request_path(Request.find_by(account_id: current_account, friend_id: friend.id)), method: :delete, data: {confirm: 'Are you sure?'},
                                            class: 'btn btn-sm btn-danger btn-block' %>
    <% elsif Request.where(account_id: friend.id, friend_id: current_account, status: 0).exists?%>
      <%= link_to 'Requested You', requests_path, class: 'btn btn-sm btn-warning btn-block'%>
    <% elsif current_account.not_friends_with?(friend.id)%>
      <% if friend.company? %>
       <%= link_to 'Follow?', friendships_path(account: friend, friend: current_account),
                            class: "btn btn-sm btn-success btn-block", method: :post %>  
      <% else %>
      <%= link_to 'Connect?', requests_path(friend: friend),
                            class: "btn btn-sm btn-success btn-block", method: :post %>   
      <% end %>              
    <% else %>
         <%= link_to 'Disconnect', friendship_path(friend), method: :delete, data: {confirm: 'Are you sure?'},
                                          class: 'btn btn-sm btn-danger btn-block' %> 
    <% end  %>
    </td>                         
    </tr>
  <% end %>
  </tbody>
  </table>
  </div>
<% end %> 
<% end %>

app/views/accounts/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'accounts/friend_result.html' %>' 

app/views/accounts/_view_connection.html.erb
<div class="row">
  <div class="col-9">  
    <table class="table table-bordered table-hover"> 
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>  
            <td><%= friend.email %></td>
            <td><%= friend.full_name %></td>
            <td><%= link_to 'View Profile', account_path(friend),
                                          class: 'btn btn-sm btn-warning' %>
            <% if !current_account.not_friends_with?(friend.id) && !(current_account == friend) %>
            <%= link_to 'Disconnect', friendship_path(friend), method: :delete, data: {confirm: 'Are you sure?'},
                                          class: 'btn btn-sm btn-danger' %></td>
            <% elsif friend.company? %>
            <%= link_to 'Follow', friendships_path(account: friend, friend: current_account),
                            class: "btn btn-sm btn-success", method: :post %>  
            <% elsif !(current_account == friend) %>
            <%= link_to 'Connect', requests_path(friend: friend),
                                  class: "btn btn-sm btn-success mt-1", method: :post %>    
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/accounts/my_friends.html.erb
<h1>Friends</h1>
<div class="w-100 p-3">
<div class="row">
<div class="col-md-6">
<h3>Your Connections</h3>
<% if @friends.count > 0 %>
  <%= render 'friends/list' %>
<% else %>
  <h5>Sorry, you have no friends!!!</h5>
<% end %> 
</div>
<div class="col-md-2">
</div>
<div class="col-md-4">
<h3>You Requested</h3>
<% if @requests.count == 0 %>
<h5>You have not requested anyone yet</h5>
<% else %>
  <table class="table table-bordered table-hover" style="text-align: center;"> 
      <thead>
        <tr>
          <th scope="col" style="width: 120px">Name</th>
          <th scope="col" style="width: 20px">Actions</th>
        </tr>
      </thead>
      <tbody>
  <% @requests.each do |request|%>
  <tr>
    <% acc = Account.find(request.friend_id) %>
    <td><%= link_to acc.full_name, account_path(acc)%></td>
       <td> <%= link_to 'Undo', request_path(request), method: :delete, data: {confirm: 'Are you sure?'},
                                                class: 'btn btn-sm btn-warning' %></td>
    </tr>
    <% end %>
  </tbody>
    </table>
    
<% end %>
<div>
</div>
</div>

app/views/accounts/search_new.html.erb
<h1>Search</h1>

<div class="w-100 p-3">
<div class="row">
<div class="col-md-7">
<div class='search-area'>
  <h3>Search Friends</h3> 
  <%= form_tag search_friends_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>


<div id="friend-results">

</div>

</div>
<div class="col-md-5 mt-5">
  <h3>Suggestions</h3>
  <div class="row">
    <% @suggested_accounts.each do |account|%>
    <div class="col-md-5 mt-2">
      <div class="card text-center" style="width: 10rem;">
        <div class="card-body">
        <% if account.image.present? %>
          <%= image_tag(account.image.variant(resize: "120x100"), :class => "rounded-circle")%>
        <% else %>
          <%= image_tag("empty_profile.jpeg", :size => '100x100', :class => "rounded-circle")%>
        <% end %><br/>
        <%= link_to account.full_name, account_path(account)%>
        <% if account.company? %>
            <%= link_to 'Follow?', friendships_path(account: current_account, friend: account),
                                  class: "btn btn-sm btn-success mt-1", method: :post %>  
            <% else %><br/>
            <%= link_to 'Connect?', requests_path(friend: account),
                                  class: "btn btn-sm btn-success mt-1", method: :post %>   
            <% end %>  <br/>
          </div>
      </div>
      </div>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/accounts/show.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>

// window.onload = function() {
//     var reloading = sessionStorage.getItem("reloading");
//     if (performance.navigation.type == performance.navigation.TYPE_RELOAD){
//       document.getElementsByClassName('comment-post-hide')[0].remove();
//       console.log("asdfawf")
//       }
// }
document.getElementById("comment-button")[0].click();
window.onload = function() {
    var reloading = sessionStorage.getItem("reloading");
    if (reloading) {
        $(".comment-post-hide").hide();
    }
}

function toggleComment(post_id){
  $(".comment-icon-post-"+post_id).toggle("fast");
  $(".comment-cursor").focus();
}
</script>

<div class="container">


<div class="container-fluid col-8"> 
<h3> User details</h3>
<% if @acc.image.present? %>
  <%= image_tag(@acc.image.variant(resize: "220x220")) %>
<% else %>
   <%= image_tag("empty_profile.jpeg", :size => '220x220')%>
<% end %>

<div class="card card-header results-block justify-content-md-center ml-5 ">

<table class="col-md-12">
  <tbody>

  <tr>
  <td><strong>Name: </strong> <%= @acc.full_name %></td> 
  </tr>
  <tr>
  <td><strong>Email: </strong> <%= @acc.email %></td>                       
  </tr>
  <tr></tr>
  <% if @acc == current_account || Friendship.where(account_id: current_account.id, friend_id: @acc.id).present? || Friendship.where(account_id: @acc.id, friend_id: current_account.id).present? || @acc.company?%>
  <tr>
  <td><%= link_to "Connections", view_connections_path(account_id: @acc.id)%></td>
  </tr>
  <% end %>
</tbody>
</table>
<% if !(current_account == @acc)%>
  <% if !current_account.not_friends_with?(@acc.id) && !(current_account == @acc) %>
    <%= link_to 'Disconnect', friendship_path(@acc), method: :delete, data: {confirm: 'Are you sure?'},
                                  class: 'btn btn-sm btn-danger' %></td>
  <% elsif Request.where(account_id: current_account, friend_id: @acc, status: 0).exists?%>
      <%= link_to 'Undo Request', request_path(Request.find_by(account_id: current_account, friend_id: @acc.id)), method: :delete, data: {confirm: 'Are you sure?'},
                                            class: 'btn btn-sm btn-warning' %> 
  <% elsif Request.where(account_id: @acc.id, friend_id: current_account, status: 0).exists?%>
      <%= link_to 'Requested You', requests_path, class: 'btn btn-sm btn-success'%>                                                                         
  <% elsif @acc.company? %>
    <%= link_to 'Follow', friendships_path(account: @acc, friend: current_account),
                    class: "btn btn-sm btn-success", method: :post %>  
  <% elsif !(current_account == @acc) %>
    <%= link_to 'Connect', requests_path(friend: @acc),
                          class: "btn btn-sm btn-success mt-1", method: :post %>    
  <% end %> 
<% end %>
</div>
<% if @acc == current_account || Friendship.where(account_id: current_account.id, friend_id: @acc.id).present? || Friendship.where(account_id: @acc.id, friend_id: current_account.id).present? || current_account.company? || @acc.company?%>
<% if @posts.count == 0 %>
  <h3><center class="mt-5">The user has no posts</center></h3>
<% end %>
  <% @posts.each do |post| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="bg-white card-header font-italic">
          <div class="bg-white">
                  <div class="d-flex flex-row user-info">
                  <% if @acc.image.present? %>
                    <%= image_tag(@acc.image.variant(resize_to_fill: [40, 40]), class: "rounded-circle") %>
                  <% else %>
                    <%= image_tag ("empty_profile.jpeg"), class: "rounded-circle profile_pic"%>
                  <% end %>
                      <div class="d-flex flex-column justify-content-start ml-2"><span class="d-block font-weight-bold name"><%= link_to post.account.full_name, account_path(post.account) %></span><span class="date text-black-50 text-left"><%= time_ago_in_words(post.created_at) %> ago</span></div>
                      <% if Account.find(post.account_id) == current_account%>
                    <div><%= link_to "Delete", post_path(post), class: "btn btn-outline-danger float-right delete-button-in-acc", method: :delete, data: {confirm: "Are you sure?"} %></div>
                      <% end %>
                  </div>
                </div>
          </div>

        <div class="mt-1">
         <% if post.images.count == 1 %>
          <%= image_tag post.images.first.variant(resize: "450x450") %>
          <% elsif post.images.count > 1 %>
          <div id="carouselExampleControls-<%= post.id.to_s %>" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
          <% post.images.each do |photo| %>
            <% if photo == post.images.first %>
              <div class="carousel-item active">
            <% else %>
              <div class="carousel-item">
            <% end %>
            <%= image_tag photo.variant(resize: "450x450") %>
            </div>
          <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls-<%= post.id.to_s %>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls-<%= post.id.to_s %>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <% end %>
        </div>
          <div class="card-body text-left">
            <p class="card-text"><%= truncate(post.description, length: 100) %></p>
            </div>
          <div class="d-flex justify-content-center row">
              <div class="col-md-12">
                  <div class="d-flex flex-column comment-section">
                      
                      <div class="card bg-white">
                          <div class="d-flex flex-row fs-12 mt-2">
                              <!-- <div class="like p-2 cursor"><i class="fa fa-thumbs-o-up"><span class="ml-1"  >Like</span></i></div> -->
                              <div id="like-icon-post-<%= post.id.to_s%>" class="ml-5">
                              <%= render "posts/like_icon", {is_liked: post.is_liked(current_account), post: post}%>
                              </div>
                              <div class="like cursor comment ml-5"><button onclick="toggleComment(<%= post.id.to_s%>)" class="like-button" id="comment-button"><i class="fa fa-commenting-o"><span class="ml-1">Comment</span></i></button></div>
                              
                          </div>
                          <div class="card bg-white mt-2">
                          <div id="like-text-post-<%= post.id.to_s %>">
                            <%= render "posts/like_text", {likes: post.likes}%>
                          </div>
                          </div>
                      </div>
                      <div class="comment-post-hide">
                        <div class="comment-icon-post-<%= post.id.to_s%>">
                          <div class="container">
                          <div class="bg-light p-2">
                            <div class="row actions" id="comment-form-post-<%= post.id.to_s%>">
                              <%= render "posts/comment_form", {post: post}%>
                            </div>
                          </div>
                          </div>
                          <div id="comment-post-<%= post.id.to_s%>">
                            <%= render "posts/comment_list", {post: post}%>
                          </div>
                        </div>
                      </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
<h3><center class="mt-5">Please connect to view their posts and connections</center></h3>
<% end %>
</div>
</div>

app/views/accounts/view_connections.html.erb
<h2><%= link_to @account1.first_name, account_path(@account1)%>'s Connections </h2>

<% if @friends.count > 0 %>
  <%= render 'accounts/view_connection' %>
<% end %> 